### PR TITLE
Adding ip6_addr for vpnclient and replacing all i.e. by e.g.

### PR DESCRIPTION
**Pull request by jvaubourg**
All is in the title.

The vpnclient ip6_addr setting is not useful in this case, but the config is not consistent in this state

### CODE REVIEW

**Comment by Kloadut** [comment]
Ok, it currently works fine, is that normal ? :)

**Comment by jvaubourg** [comment]
Yep, replacing all i.e. by e.g. has no influence on the script :).

More seriously, the missing of ::42 on vpnclient is not a problem in your case, because hotspot is in charge of this address when it is installed. But in a generated configuration, the ip6_addr setting is set in vpnclient when the ip6_net setting is set. This anomaly could be a problem in the future (I don't know why or when, but someone could use ip6_addr in the service without checking, because it is theoretically available in the case of ip6_net is set), or if the user decides to uninstall hotspot.

**Comment by sbadia** [comment]
any blocking point here ? we can merge this pr ?

**Comment by Psycojoker** [comment]
"up" (while I don't understand anything about this patch)

**Comment by jvaubourg** [comment]
This patch just adds the default IPv6 address, as vpnclient adds it when you configure an IPv6 prefix through the web admin. I do not understand what is your problem with this PR :).

**Comment by Psycojoker** [comment]
Probably no one to read/validate it, appart from the fact that the branches have diverged.

@Kloadut ping? Any opinion?

**Comment by Kloadut** [comment]
Already merged actually: https://github.com/labriqueinternet/configuration_scripts/blob/master/neutrinet.sh#L197

**Comment by jvaubourg** [comment]
Thank you @Kloadut . But, you should also take in account the replacement of all "i.e." (= "in other words")  by "e.g." (= "for example"). This was a part of this PR.

**Comment by Kloadut** [comment]
Yup, will do

**Pull request closed without merging**
